// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAegeGbAZPS5mgjvGxpXSfUhcsyIkH_dj0',
    appId: '1:437280871209:web:4d560b928a9b9361169d38',
    messagingSenderId: '437280871209',
    projectId: 'sound-to-vision-8832a',
    authDomain: 'sound-to-vision-8832a.firebaseapp.com',
    storageBucket: 'sound-to-vision-8832a.firebasestorage.app',
    measurementId: 'G-79ERL7D003',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFgKywpGk6094KrgE04wsUsfxB__Xg-E',
    appId: '1:437280871209:android:9877300346d2c253169d38',
    messagingSenderId: '437280871209',
    projectId: 'sound-to-vision-8832a',
    storageBucket: 'sound-to-vision-8832a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTE1JABdm-y2owUmmzJ0WzzNW9-tjvajs',
    appId: '1:437280871209:ios:7d2514b3629e4fba169d38',
    messagingSenderId: '437280871209',
    projectId: 'sound-to-vision-8832a',
    storageBucket: 'sound-to-vision-8832a.firebasestorage.app',
    iosBundleId: 'com.example.soundToVisionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTE1JABdm-y2owUmmzJ0WzzNW9-tjvajs',
    appId: '1:437280871209:ios:7d2514b3629e4fba169d38',
    messagingSenderId: '437280871209',
    projectId: 'sound-to-vision-8832a',
    storageBucket: 'sound-to-vision-8832a.firebasestorage.app',
    iosBundleId: 'com.example.soundToVisionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAegeGbAZPS5mgjvGxpXSfUhcsyIkH_dj0',
    appId: '1:437280871209:web:88726df3d924fa65169d38',
    messagingSenderId: '437280871209',
    projectId: 'sound-to-vision-8832a',
    authDomain: 'sound-to-vision-8832a.firebaseapp.com',
    storageBucket: 'sound-to-vision-8832a.firebasestorage.app',
    measurementId: 'G-X0B55KGX0N',
  );
}
